name: Evaluate Challenge
on:
  issues:
    types: [opened, edited]
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo '${{ github.event.issue.body }}'
        name: Print Issue Body
      
      - uses: stefanbuck/github-issue-parser@v3
        id: challenge-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/challenge.yaml
          
      - run: echo '${{ steps.challenge-parser.outputs.jsonString }}'
        name: Print Parser result

      - run: echo '${{ steps.challenge-parser.outputs.jsonString }}' | jq '.repo_first | split("/")[0]'

      - name: Ottieni il numero di stelle del repository
        id: stars
        uses: octokit/graphql-action@v2.x
        with:
          graphql: |
            query getstars($owner:String!, $repo:String!) {
              repository(owner: $owner, name: $name) {
                stargazers {
                  totalCount
                }
              }
            }
          owner: gohugoio
          name: hugo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


